name: Cross-Platform Build

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allows manual triggering

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker build -t nocheat-builder .

      - name: Run cross-compilation
        run: docker run --rm -v ${{ github.workspace }}:/app nocheat-builder

      - name: Upload Linux static library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-static-build
          path: target/release-builds/libnocheat_linux_x86_64.a
          if-no-files-found: error
          
      - name: Upload Linux dynamic library artifacts
        uses: actions/upload-artifact@v4
        with:
          name: linux-dynamic-build
          path: target/release-builds/libnocheat_linux_x86_64.so
          if-no-files-found: error

      - name: Upload Windows build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: windows-build
          path: target/release-builds/nocheat_windows_x86_64.dll
          if-no-files-found: error